baseURL = 'https://ericpardee.com'
languageCode = 'en-us'
title = 'ericpardee.com'
theme = 'hugo-book'

[deployment]

[[deployment.targets]]
# Name for this target.
name = "ericpardee.com"
URL = "s3://ericpardee.com?region=us-west-2"